GET http://localhost:1854/user

###
GET http://localhost:1854/user/10

###
POST http://localhost:1854/user
Content-Type: application/json

{
    "name" : "Temi",
     "user": "Temibillions"
    }

###
GET http://localhost:1854/user/63cfc2ecee27306fe609783f

### 
PATCH http://localhost:1854/user/63cfc2ecee27306fe609783f
Content-Type: application/json

{
    "name": "Raj Singer",
    "subscribedToChannel": "code with vscode1"
}

###
DELETE http://localhost:1854/user/63cfc2ecee27306fe609783f